# This is an ansible script of the instructions from this site   https://tecadmin.net/install-python-3-8-centos/
#
# Yaml file to install python3.8, clean up, and set up a symlink for `python3`
#
- hosts: all
  gather_facts: no
  tasks:
    # Checking to see if I can talk to the box
    - name: can i talk to myself
      ping: 
      register: out
    
    # How to do print statements in ansible, not required
    - name: printing the results of the ping command 
      debug:
        var: out

    - name: find all files with the repo suffix to delete
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: to_delete

    - name: delete all repo files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ to_delete.files }}" 
      become: yes

    - name: create file so yum points at local repo
      copy:
        dest: "/etc/yum.repos.d/remote.repo"
        content: |
          [remote]
          name=YUM Local
          baseurl=http://192.168.56.99
          enable=1
          gpgcheck=0
      become: yes

    - name: install packages required to compile python 
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - gcc
          - openssl-devel
          - bzip2-devel
          - libffi-devel
      become: yes 

    - name: Download an unarchive the python files
      unarchive:
        src: http://192.168.56.99/Python-3.8.0.tgz
        dest: /home/ansible
        remote_src: yes

    - name: enable optimizations in python3.8
      command: ./configure --enable-optimizations
      args:
        chdir: "/home/ansible/Python-3.8.0"
      become: yes
      
    - name: make python3.8
      command: make altinstall 
      args:
        chdir: "/home/ansible/Python-3.8.0"
      become: yes

    - name: Cleanup downloaded files
      file:
        state: absent
        path: "/home/ansible/Python-3.8.0/"
      become: yes

    - name: Create a python3 symlink
      file:
        src: "/usr/local/bin/python3.8"
        dest: "/usr/local/bin/python3"
        state: link
      become: yes

