# Yaml file to install python3, clone a repo, and install dependencies
- hosts: all
  gather_facts: no
  tasks:
    # Checking to see if I can talk to the box
    - name: can i talk to myself
      ping: 
      register: out
    
    # How to do print statements in ansible
    - name: output results of the ping command 
      debug:
        var: out
    
    # Here's how to do some testing, not really required
    - name: stop if i couldn't connect
      assert:
        that: "{{ out.failed }} == false"

    - name: find all files with the repo suffix to delete
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: to_delete

    - name: delete all repo files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ to_delete.files }}" 
      become: yes

    - name: create file so yum points at local repo
      copy:
        dest: "/etc/yum.repos.d/remote.repo"
        content: |
          [remote]
          name=YUM Local
          baseurl=http://192.168.56.99
          enable=1
          gpgcheck=0
      become: yes

    # I like vim rather than vi
    - name: install vim
      yum:
        name: vim
        state: latest
      become: yes

    # Setuptools needs to be installed for the python interpreter running Ansible to use the pip module
    - name: install required OS packages so the rest of the process will work
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - gcc
          - python-setuptools
          - python3
          - python3-pip
          - python3-devel
          - git
          - unzip
      become: yes 

    - name: install packages for general python3 development 
      pip:
        name: 
          - pipenv
          - flake8
          - pytest
          - pytest-cov
        executable: pip3
        extra_args: --user
   
    - name: install tinydb-sample-blog from zip file
      unarchive:
        src: http://192.168.56.99/tinydb-sample-blog-master.zip
        dest: /home/ansible
        remote_src: yes
    
    - name: setup a virtual environment and install required packages
      command: ~/.local/bin/pipenv install -r src/requirements.txt
      args:
        chdir: /home/ansible/tinydb-sample-blog-master

